#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ auto-close-prs
Automatically close PRs that don't match the contribution guidelines.

Uses the github cli and https://github.com/xirzec/gh-notifications

Run via systemd timers: https://github.com/jneidel/dotfiles/commit/52bd4ec
EOF
  exit
fi

hash gh gron || exit 127

get_pr_url_from_list_index() {
  n=$1
  gh pr list --json url | jq -r ".[$n].url"
}
get_issue_url_from_list_index() {
  n=$1
  gh issue list --json url | jq -r ".[$n].url"
}

mark_notification_done() {
  title="$1"
  notificationType="$2"
  [ -z "$notificationType" ] && notificationType="PR"

  gh notifications -R agarrharr/awesome-cli-apps \
     --type $notificationType --state closed --filter "$title" \
     --mark-read --yes 2>/dev/null
}

gh pr list --json body | gron | grep -v contributing.md |
  grep -F ".body" | cut -d\[ -f2 | cut -d\] -f1 |
  while read index; do
    url="$(get_pr_url_from_list_index $index)"
    title="$(gh pr list --json title | gron | grep -F "json[$index].title" | cut -d\" -f2)"
    echo "Closing: contributing.md not mentioned (i.e. pr template was ignored.)" >&2
    gh pr close "$url"
    mark_notification_done "$title"
  done

gh pr list --json body | gron | grep -F "I did not read the contribution guidelines." |
  grep -F ".body" | cut -d\[ -f2 | cut -d\] -f1 |
  while read index; do
    url="$(get_pr_url_from_list_index $index)"
    title="$(gh pr list --json title | gron | grep -F "json[$index].title" | cut -d\" -f2)"
    echo "Closing: user did not read." >&2
    gh pr close "$url"
    mark_notification_done "$title"
  done

gh pr list --json body | gron | grep -F ".body" |
  grep -Po "https://github.com/[A-Za-z0-9-_]+/[A-Za-z0-9-_]+" | grep -v awesome-cli-apps |
  while read repo; do
    stars=$(gh repo view --json stargazerCount -q ".stargazerCount" "$repo")
    age=$(gh repo view --json createdAt -q ".createdAt" "$repo")
    index=$(gh pr list --json body | gron | grep "$repo" | cut -d\[ -f2 | cut -d\] -f1)
    url="$(get_pr_url_from_list_index $index)"
    title="$(gh pr list --json title | gron | grep -F "json[$index].title" | cut -d\" -f2)"

    if [ "$stars" -lt 20 ]; then
      echo "Closing: star requirement not met." >&2
      gh pr close "$url" --comment "Closed by bot: Star requirement not met."
      mark_notification_done "$title"
    elif [ "$(date -d "$age" +%s)" -gt "$(date -d "-3 months" +%s)" ]; then
      echo "Closing: age requirement not met." >&2
      gh pr close "$url" --comment "Closed by bot: Repo age requirement not met."
      mark_notification_done "$title"
    fi
  done

gh issue list --json title | gron | grep '"Add' |
  grep -F ".title" | cut -d\[ -f2 | cut -d\] -f1 |
  while read index; do
    url="$(get_issue_url_from_list_index $index)"
    title="$(gh issue list --json title | gron | grep -F "json[$index].title" | cut -d\" -f2)"
    echo "Closing: Issues adds an app" >&2
    gh issue close "$url" --comment "Closed by bot: Issues that add apps are no longer considered. Please open a PR instead."
    mark_notification_done "$title" "issue"
  done
