#! /bin/sh

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "help" ]; then
  cat <<EOF
$ auto-close-prs
Automatically close PRs that don't match the contribution guidelines.

Run via systemd timers: https://github.com/jneidel/dotfiles/commit/52bd4ec
EOF
  exit
fi

hash gh gron || exit 127

DIR=`dirname $0`
cd $DIR

get_pr_url_from_list_index() {
  n=$1
  gh pr list --json url | jq -r ".[$n].url"
}

gh pr list --json body | gron | grep -v contributing.md | grep body | cut -d\[ -f2 | cut -d\] -f1 |
  while read index; do
    url="$(get_pr_url_from_list_index $index)"
    echo "Closing: contributing.md not mentioned (i.e. pr template was ignored.)" >&2
    gh pr close "$url"
  done

gh pr list --json body | gron | grep "body" |
  grep -Po "https://github.com/[A-Za-z0-9-]+/[A-Za-z0-9-]+" | grep -v awesome-cli-apps |
  while read repo; do
    stars=$(gh repo view --json stargazerCount -q ".stargazerCount" "$repo")
    age=$(gh repo view --json createdAt -q ".createdAt" "$repo")
    index=$(gh pr list --json body | gron | grep "$repo" | cut -d\[ -f2 | cut -d\] -f1)
    url="$(get_pr_url_from_list_index $index)"

    if [ "$stars" -lt 20 ]; then
      echo "Closing: star requirement not met." >&2
      gh pr close "$url" --comment "Closed by bot: Star requirement not met."
    elif [ "$(date -d "$age" +%s)" -gt "$(date -d "-3 months" +%s)" ]; then
      echo "Closing: age requirement not met." >&2
      gh pr close "$url" --comment "Closed by bot: Repo age requirement not met."
    fi
  done
